### PR TITLE
Monobranch

### PR DESCRIPTION
**Pull request by nrolland**
This branch is meant to work on mono

### CODE REVIEW

**Comment by nrolland** [comment]
not sure if this should go in master

**Comment by crusso** [comment]
Pourquois pas?

**Comment by crusso** [comment]
Yeah, it looks like there's a mix of unix and windows paths in some of the files. Asking for trouble...

**Comment by nrolland** [comment]
it can always be merged later on once we are confident it works

On Thu, Oct 15, 2015 at 4:43 PM, crusso notifications@github.com wrote:

> Yeah, it looks like there's a mix of unix and windows paths in some of the
> files. Asking for trouble...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TabularLang/CoreTabular/pull/1#issuecomment-148407752
> .

## 

Nicolas Rolland
mobile : +33 6 62 88 42 92

**Comment by nrolland** [comment]
merging is really easy with git, so there are few or none overhead cost

On Thu, Oct 15, 2015 at 4:57 PM, Nicolas R nicolas.rolland@gmail.com
wrote:

> it can always be merged later on once we are confident it works
> 
> On Thu, Oct 15, 2015 at 4:43 PM, crusso notifications@github.com wrote:
> 
> > Yeah, it looks like there's a mix of unix and windows paths in some of
> > the files. Asking for trouble...
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/TabularLang/CoreTabular/pull/1#issuecomment-148407752
> > .
> 
> ## 
> 
> Nicolas Rolland
> mobile : +33 6 62 88 42 92

## 

Nicolas Rolland
mobile : +33 6 62 88 42 92

**Comment by crusso** [comment]
Ok, but I just did some manual    to the main branch that you may want to pull furst

Sent from my Windows Phone

**Comment by nrolland** [comment]
Ok, I will [rebase](https://fr.atlassian.com/git/tutorials/rewriting-history/git-rebase)

Another thing to be careful with : Line endings. 
Text editors should be set to NOT touch (which is not the default in Xamarin) what they receive from git, which does everything correctly AFAIK

**Comment by crusso** [comment]
Do I need to instruct VS to do anything?

**Pull request closed without merging**
